// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(orchard_keys_uniffiFFI)
import orchard_keys_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_orchard_keys_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_orchard_keys_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public protocol OrchardAddressProtocol {
    func stringEncoded()   -> String
    
}

public class OrchardAddress: OrchardAddressProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_orchard_keys_uniffi_fn_free_orchardaddress(pointer, $0) }
    }

    

    public static func newFromString(string: String) throws -> OrchardAddress {
        return OrchardAddress(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardaddress_new_from_string(
        FfiConverterString.lower(string),$0)
})
    }

    

    
    

    public func stringEncoded()  -> String {
        return try!  FfiConverterString.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardaddress_string_encoded(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeOrchardAddress: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchardAddress

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardAddress {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchardAddress, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardAddress {
        return OrchardAddress(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchardAddress) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeOrchardAddress_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardAddress {
    return try FfiConverterTypeOrchardAddress.lift(pointer)
}

public func FfiConverterTypeOrchardAddress_lower(_ value: OrchardAddress) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchardAddress.lower(value)
}


public protocol OrchardCommitIvkRandomnessProtocol {
    func toBytes()   -> Data
    
}

public class OrchardCommitIvkRandomness: OrchardCommitIvkRandomnessProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(bytes: Data) throws {
        self.init(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardcommitivkrandomness_new(
        FfiConverterData.lower(bytes),$0)
})
    }

    deinit {
        try! rustCall { uniffi_orchard_keys_uniffi_fn_free_orchardcommitivkrandomness(pointer, $0) }
    }

    

    
    

    public func toBytes()  -> Data {
        return try!  FfiConverterData.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardcommitivkrandomness_to_bytes(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeOrchardCommitIvkRandomness: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchardCommitIvkRandomness

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardCommitIvkRandomness {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchardCommitIvkRandomness, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardCommitIvkRandomness {
        return OrchardCommitIvkRandomness(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchardCommitIvkRandomness) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeOrchardCommitIvkRandomness_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardCommitIvkRandomness {
    return try FfiConverterTypeOrchardCommitIvkRandomness.lift(pointer)
}

public func FfiConverterTypeOrchardCommitIvkRandomness_lower(_ value: OrchardCommitIvkRandomness) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchardCommitIvkRandomness.lower(value)
}


public protocol OrchardFullViewingKeyProtocol {
    func ak()   -> OrchardSpendValidatingKey
    func deriveAddress()  throws -> OrchardAddress
    func encode()  throws -> String
    func nk()   -> OrchardNullifierDerivingKey
    func rivk()   -> OrchardCommitIvkRandomness
    
}

public class OrchardFullViewingKey: OrchardFullViewingKeyProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_orchard_keys_uniffi_fn_free_orchardfullviewingkey(pointer, $0) }
    }

    

    public static func decode(stringEnconded: String, network: ZcashNetwork) throws -> OrchardFullViewingKey {
        return OrchardFullViewingKey(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardfullviewingkey_decode(
        FfiConverterString.lower(stringEnconded),
        FfiConverterTypeZcashNetwork.lower(network),$0)
})
    }

    

    public static func newFromCheckedParts(ak: OrchardSpendValidatingKey, nk: OrchardNullifierDerivingKey, rivk: OrchardCommitIvkRandomness, network: ZcashNetwork) throws -> OrchardFullViewingKey {
        return OrchardFullViewingKey(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardfullviewingkey_new_from_checked_parts(
        FfiConverterTypeOrchardSpendValidatingKey.lower(ak),
        FfiConverterTypeOrchardNullifierDerivingKey.lower(nk),
        FfiConverterTypeOrchardCommitIvkRandomness.lower(rivk),
        FfiConverterTypeZcashNetwork.lower(network),$0)
})
    }

    

    public static func newFromValidatingKeyAndSeed(validatingKey: OrchardSpendValidatingKey, zip32Seed: Data, network: ZcashNetwork) throws -> OrchardFullViewingKey {
        return OrchardFullViewingKey(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardfullviewingkey_new_from_validating_key_and_seed(
        FfiConverterTypeOrchardSpendValidatingKey.lower(validatingKey),
        FfiConverterData.lower(zip32Seed),
        FfiConverterTypeZcashNetwork.lower(network),$0)
})
    }

    

    
    

    public func ak()  -> OrchardSpendValidatingKey {
        return try!  FfiConverterTypeOrchardSpendValidatingKey.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardfullviewingkey_ak(self.pointer, $0
    )
}
        )
    }

    public func deriveAddress() throws -> OrchardAddress {
        return try  FfiConverterTypeOrchardAddress.lift(
            try 
    rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_method_orchardfullviewingkey_derive_address(self.pointer, $0
    )
}
        )
    }

    public func encode() throws -> String {
        return try  FfiConverterString.lift(
            try 
    rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_method_orchardfullviewingkey_encode(self.pointer, $0
    )
}
        )
    }

    public func nk()  -> OrchardNullifierDerivingKey {
        return try!  FfiConverterTypeOrchardNullifierDerivingKey.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardfullviewingkey_nk(self.pointer, $0
    )
}
        )
    }

    public func rivk()  -> OrchardCommitIvkRandomness {
        return try!  FfiConverterTypeOrchardCommitIvkRandomness.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardfullviewingkey_rivk(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeOrchardFullViewingKey: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchardFullViewingKey

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardFullViewingKey {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchardFullViewingKey, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardFullViewingKey {
        return OrchardFullViewingKey(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchardFullViewingKey) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeOrchardFullViewingKey_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardFullViewingKey {
    return try FfiConverterTypeOrchardFullViewingKey.lift(pointer)
}

public func FfiConverterTypeOrchardFullViewingKey_lower(_ value: OrchardFullViewingKey) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchardFullViewingKey.lower(value)
}


public protocol OrchardKeyPartsProtocol {
    
}

public class OrchardKeyParts: OrchardKeyPartsProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_orchard_keys_uniffi_fn_free_orchardkeyparts(pointer, $0) }
    }

    

    public static func random(network: ZcashNetwork) throws -> OrchardKeyParts {
        return OrchardKeyParts(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardkeyparts_random(
        FfiConverterTypeZcashNetwork.lower(network),$0)
})
    }

    

    
    
}

public struct FfiConverterTypeOrchardKeyParts: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchardKeyParts

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardKeyParts {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchardKeyParts, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardKeyParts {
        return OrchardKeyParts(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchardKeyParts) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeOrchardKeyParts_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardKeyParts {
    return try FfiConverterTypeOrchardKeyParts.lift(pointer)
}

public func FfiConverterTypeOrchardKeyParts_lower(_ value: OrchardKeyParts) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchardKeyParts.lower(value)
}


public protocol OrchardNullifierDerivingKeyProtocol {
    func toBytes()   -> Data
    
}

public class OrchardNullifierDerivingKey: OrchardNullifierDerivingKeyProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(bytes: Data) throws {
        self.init(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardnullifierderivingkey_new(
        FfiConverterData.lower(bytes),$0)
})
    }

    deinit {
        try! rustCall { uniffi_orchard_keys_uniffi_fn_free_orchardnullifierderivingkey(pointer, $0) }
    }

    

    
    

    public func toBytes()  -> Data {
        return try!  FfiConverterData.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardnullifierderivingkey_to_bytes(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeOrchardNullifierDerivingKey: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchardNullifierDerivingKey

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardNullifierDerivingKey {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchardNullifierDerivingKey, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardNullifierDerivingKey {
        return OrchardNullifierDerivingKey(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchardNullifierDerivingKey) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeOrchardNullifierDerivingKey_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardNullifierDerivingKey {
    return try FfiConverterTypeOrchardNullifierDerivingKey.lift(pointer)
}

public func FfiConverterTypeOrchardNullifierDerivingKey_lower(_ value: OrchardNullifierDerivingKey) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchardNullifierDerivingKey.lower(value)
}


public protocol OrchardSpendValidatingKeyProtocol {
    func toBytes()   -> Data
    
}

public class OrchardSpendValidatingKey: OrchardSpendValidatingKeyProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_orchard_keys_uniffi_fn_free_orchardspendvalidatingkey(pointer, $0) }
    }

    

    public static func fromBytes(bytes: Data) throws -> OrchardSpendValidatingKey {
        return OrchardSpendValidatingKey(unsafeFromRawPointer: try rustCallWithError(FfiConverterTypeOrchardKeyError.lift) {
    uniffi_orchard_keys_uniffi_fn_constructor_orchardspendvalidatingkey_from_bytes(
        FfiConverterData.lower(bytes),$0)
})
    }

    

    
    

    public func toBytes()  -> Data {
        return try!  FfiConverterData.lift(
            try! 
    rustCall() {
    
    uniffi_orchard_keys_uniffi_fn_method_orchardspendvalidatingkey_to_bytes(self.pointer, $0
    )
}
        )
    }
}

public struct FfiConverterTypeOrchardSpendValidatingKey: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = OrchardSpendValidatingKey

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardSpendValidatingKey {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: OrchardSpendValidatingKey, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardSpendValidatingKey {
        return OrchardSpendValidatingKey(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: OrchardSpendValidatingKey) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeOrchardSpendValidatingKey_lift(_ pointer: UnsafeMutableRawPointer) throws -> OrchardSpendValidatingKey {
    return try FfiConverterTypeOrchardSpendValidatingKey.lift(pointer)
}

public func FfiConverterTypeOrchardSpendValidatingKey_lower(_ value: OrchardSpendValidatingKey) -> UnsafeMutableRawPointer {
    return FfiConverterTypeOrchardSpendValidatingKey.lower(value)
}

public enum OrchardKeyError {

    
    
    case KeyDerivationError(message: String)
    case SerializationError
    case DeserializationError
    case OtherError(errorMessage: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeOrchardKeyError.lift(error)
    }
}


public struct FfiConverterTypeOrchardKeyError: FfiConverterRustBuffer {
    typealias SwiftType = OrchardKeyError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OrchardKeyError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .KeyDerivationError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .SerializationError
        case 3: return .DeserializationError
        case 4: return .OtherError(
            errorMessage: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: OrchardKeyError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .KeyDerivationError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case .SerializationError:
            writeInt(&buf, Int32(2))
        
        
        case .DeserializationError:
            writeInt(&buf, Int32(3))
        
        
        case let .OtherError(errorMessage):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(errorMessage, into: &buf)
            
        }
    }
}


extension OrchardKeyError: Equatable, Hashable {}

extension OrchardKeyError: Error { }

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum ZcashNetwork {
    
    case mainnet
    case testnet
}

public struct FfiConverterTypeZcashNetwork: FfiConverterRustBuffer {
    typealias SwiftType = ZcashNetwork

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZcashNetwork {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .mainnet
        
        case 2: return .testnet
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ZcashNetwork, into buf: inout [UInt8]) {
        switch value {
        
        
        case .mainnet:
            writeInt(&buf, Int32(1))
        
        
        case .testnet:
            writeInt(&buf, Int32(2))
        
        }
    }
}


public func FfiConverterTypeZcashNetwork_lift(_ buf: RustBuffer) throws -> ZcashNetwork {
    return try FfiConverterTypeZcashNetwork.lift(buf)
}

public func FfiConverterTypeZcashNetwork_lower(_ value: ZcashNetwork) -> RustBuffer {
    return FfiConverterTypeZcashNetwork.lower(value)
}


extension ZcashNetwork: Equatable, Hashable {}



private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_orchard_keys_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardaddress_string_encoded() != 45373) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardcommitivkrandomness_to_bytes() != 39706) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardfullviewingkey_ak() != 58523) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardfullviewingkey_derive_address() != 30379) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardfullviewingkey_encode() != 10811) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardfullviewingkey_nk() != 4468) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardfullviewingkey_rivk() != 20701) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardnullifierderivingkey_to_bytes() != 35670) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_method_orchardspendvalidatingkey_to_bytes() != 7799) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardaddress_new_from_string() != 17794) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardcommitivkrandomness_new() != 26754) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardfullviewingkey_decode() != 59898) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardfullviewingkey_new_from_checked_parts() != 26001) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardfullviewingkey_new_from_validating_key_and_seed() != 23354) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardkeyparts_random() != 58205) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardnullifierderivingkey_new() != 14789) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orchard_keys_uniffi_checksum_constructor_orchardspendvalidatingkey_from_bytes() != 45379) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}
